### ISSUE TITLE
shorturl compares URLs differently

### ISSUE THREAD

**Issue by axeld** [vitorccs/yourls-api-save-by-keyword#2]
I accidentally forgot the schema prefix for my URLs. When I tried to change that via the "save_by_keyword" API, I could not, as "shorturl" would complain that the URL already exists.

**Comment by vitorccs** [comment]
@axeld I am closing this issue since this is already being discussed here https://github.com/vitorccs/yourls-api-save-by-keyword/issues/1

**Comment by axeld** [comment]
It's not really the same issue, but it might well be fixed by the same solution. I'll give it a try and report.
